
package imports;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SeriesSoapWSService", targetNamespace = "http://book/", wsdlLocation = "http://localhost:8080/soap/SeriesSoapWS?wsdl")
public class SeriesSoapWSService
    extends Service
{

    private final static URL SERIESSOAPWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERIESSOAPWSSERVICE_EXCEPTION;
    private final static QName SERIESSOAPWSSERVICE_QNAME = new QName("http://book/", "SeriesSoapWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/SeriesSoapWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERIESSOAPWSSERVICE_WSDL_LOCATION = url;
        SERIESSOAPWSSERVICE_EXCEPTION = e;
    }

    public SeriesSoapWSService() {
        super(__getWsdlLocation(), SERIESSOAPWSSERVICE_QNAME);
    }

    public SeriesSoapWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERIESSOAPWSSERVICE_QNAME, features);
    }

    public SeriesSoapWSService(URL wsdlLocation) {
        super(wsdlLocation, SERIESSOAPWSSERVICE_QNAME);
    }

    public SeriesSoapWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERIESSOAPWSSERVICE_QNAME, features);
    }

    public SeriesSoapWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeriesSoapWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SeriesSoapWS
     */
    @WebEndpoint(name = "SeriesSoapWSPort")
    public SeriesSoapWS getSeriesSoapWSPort() {
        return super.getPort(new QName("http://book/", "SeriesSoapWSPort"), SeriesSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeriesSoapWS
     */
    @WebEndpoint(name = "SeriesSoapWSPort")
    public SeriesSoapWS getSeriesSoapWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://book/", "SeriesSoapWSPort"), SeriesSoapWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERIESSOAPWSSERVICE_EXCEPTION!= null) {
            throw SERIESSOAPWSSERVICE_EXCEPTION;
        }
        return SERIESSOAPWSSERVICE_WSDL_LOCATION;
    }

}
