
package imports;

import java.math.BigDecimal;
import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SeriesSoapWS", targetNamespace = "http://book/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeriesSoapWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns imports.Serie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSerieData", targetNamespace = "http://book/", className = "imports.GetSerieData")
    @ResponseWrapper(localName = "getSerieDataResponse", targetNamespace = "http://book/", className = "imports.GetSerieDataResponse")
    public Serie getSerieData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<imports.Serie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSeries", targetNamespace = "http://book/", className = "imports.GetSeries")
    @ResponseWrapper(localName = "getSeriesResponse", targetNamespace = "http://book/", className = "imports.GetSeriesResponse")
    public List<Serie> getSeries();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRating", targetNamespace = "http://book/", className = "imports.GetRating")
    @ResponseWrapper(localName = "getRatingResponse", targetNamespace = "http://book/", className = "imports.GetRatingResponse")
    public BigDecimal getRating(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTitles", targetNamespace = "http://book/", className = "imports.GetTitles")
    @ResponseWrapper(localName = "getTitlesResponse", targetNamespace = "http://book/", className = "imports.GetTitlesResponse")
    public List<String> getTitles();

}
